name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args:
              -Dsonar.organization=yoniiii
              -Dsonar.projectKey=Yoniiii_cd
        - uses: sburris/dependency-check-action@master
          with:
            Project-Name: TestApp
        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: sonar_reports
            path: reports

        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: yoniperetti/cd
            tag_with_sha: true

        - name: Set outputs
          id: vars
          run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: docker.io/3r1co/cd:sha-${{ steps.vars.outputs.sha_short }}
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'