name: Build App

on:
    push:
        branches:
        - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install NPM dependencies
          run: |
            npm install --production --unsafe-perm
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            projectBaseDir: .
            args:
              -Dsonar.organization=Yoniiii_cd
              -Dsonar.projectKey=yoniiii
        - name: Archive dependency check reports
          uses: actions/upload-artifact@v1
          with:
            name: reports
            path: .
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            registry: docker.io
            repository: yoniperetti/cd
            tag_with_sha: true